### ISSUE TITLE
Add dynamic title functionality

### ISSUE THREAD

**Issue by magooken** [line/conflr#106]
When I tried to use a YAML param to create a dynamic title, it showed up fine when I knit it, but in the confluence page, it just showed the R code.
`---
output: html_document
params:
  peril: 'Peril Name'
  version: 0.03
title: "`r paste0(params$peril,' - v', params$version,'a')`"
---`

**Comment by yutannihilation** [comment]
Hmm, curious. Thanks for reporting.

**Comment by yutannihilation** [comment]
@magooken 
Sorry, I couldn't reproduce your problem. On my Confluence the page is titled as intended ("Peril Name - v0.03a"). Do you use the latest CRAN version of conflr?

**Comment by magooken** [comment]
Thank for looking into this. I'm using version 0.1.1 in R 3.5.3. Does it matter how I'm knitting it? I'm using an Rscript call to conflr::confl_create_post_from_Rmd.

**Comment by yutannihilation** [comment]
Aw, thanks for the detail! I used addin so this is the difference.

For a reason `conflr::confl_create_post_from_Rmd()` is a bit tricky, so I need to think if I really can fix this issue properly.

Meanwhile, I have two possible workarounds in my mind:

One is to override `title` in the script.

``` r
conflr::confl_create_post_from_Rmd("path/to/Rmd", title = paste0(...))
```

But, you are trying to use `param` in the Rmd, so it seems not the case...

Another is use `conflr::confluence_document` instead of `html_document` so that you can just `rmarkdown::render()` instead of `conflr::confl_create_post_from_Rmd()`.

```
---
output:
  conflr::confluence_document:
    space_key: "..."
    update: true
params:
  peril: 'Peril Name'
  version: 0.03
title: "`r paste0(params$peril,' - v', params$version,'a')`"
---
```
